package dominio;
// Generated 22/07/2015 11:18:12 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Concurso generated by hbm2java
 */
public class Concurso  implements java.io.Serializable {


     private String numeroResolucionConcurso;
     private Resolucion resolucion;
     private int idConcurso;
     private Date fechaConcurso;
     private String resultado;
     private Integer cantidadCubierto;

    public Concurso() {
    }

	
    public Concurso(String numeroResolucionConcurso, int idConcurso) {
        this.numeroResolucionConcurso = numeroResolucionConcurso;
        this.idConcurso = idConcurso;
    }
    public Concurso(String numeroResolucionConcurso, Resolucion resolucion, int idConcurso, Date fechaConcurso, String resultado, Integer cantidadCubierto) {
       this.numeroResolucionConcurso = numeroResolucionConcurso;
       this.resolucion = resolucion;
       this.idConcurso = idConcurso;
       this.fechaConcurso = fechaConcurso;
       this.resultado = resultado;
       this.cantidadCubierto = cantidadCubierto;
    }
   
    public String getNumeroResolucionConcurso() {
        return this.numeroResolucionConcurso;
    }
    
    public void setNumeroResolucionConcurso(String numeroResolucionConcurso) {
        this.numeroResolucionConcurso = numeroResolucionConcurso;
    }
    public Resolucion getResolucion() {
        return this.resolucion;
    }
    
    public void setResolucion(Resolucion resolucion) {
        this.resolucion = resolucion;
    }
    public int getIdConcurso() {
        return this.idConcurso;
    }
    
    public void setIdConcurso(int idConcurso) {
        this.idConcurso = idConcurso;
    }
    public Date getFechaConcurso() {
        return this.fechaConcurso;
    }
    
    public void setFechaConcurso(Date fechaConcurso) {
        this.fechaConcurso = fechaConcurso;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    public Integer getCantidadCubierto() {
        return this.cantidadCubierto;
    }
    
    public void setCantidadCubierto(Integer cantidadCubierto) {
        this.cantidadCubierto = cantidadCubierto;
    }




}


