package dominio;
// Generated 24/07/2015 09:37:24 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Establecimiento generated by hbm2java
 */
public class Establecimiento  implements java.io.Serializable {


     private long codigoSiisa;
     private int idEstablecimiento;
     private String nombre;
     private String departamento;
     private String dependencia;
     private String tipologia;
     private String localidad;
     private String categoria;
     private String domicilio;
     private String responsable;
     private String telefono;
     private String origenDeFinanciamiento;
     private Short nivel;
     private Set cargos = new HashSet(0);
     private Set tribunalJurados = new HashSet(0);

    public Establecimiento() {
    }

	
    public Establecimiento(long codigoSiisa, int idEstablecimiento) {
        this.codigoSiisa = codigoSiisa;
        this.idEstablecimiento = idEstablecimiento;
    }
    public Establecimiento(long codigoSiisa, int idEstablecimiento, String nombre, String departamento, String dependencia, String tipologia, String localidad, String categoria, String domicilio, String responsable, String telefono, String origenDeFinanciamiento, Short nivel, Set cargos, Set tribunalJurados) {
       this.codigoSiisa = codigoSiisa;
       this.idEstablecimiento = idEstablecimiento;
       this.nombre = nombre;
       this.departamento = departamento;
       this.dependencia = dependencia;
       this.tipologia = tipologia;
       this.localidad = localidad;
       this.categoria = categoria;
       this.domicilio = domicilio;
       this.responsable = responsable;
       this.telefono = telefono;
       this.origenDeFinanciamiento = origenDeFinanciamiento;
       this.nivel = nivel;
       this.cargos = cargos;
       this.tribunalJurados = tribunalJurados;
    }
   
    public long getCodigoSiisa() {
        return this.codigoSiisa;
    }
    
    public void setCodigoSiisa(long codigoSiisa) {
        this.codigoSiisa = codigoSiisa;
    }
    public int getIdEstablecimiento() {
        return this.idEstablecimiento;
    }
    
    public void setIdEstablecimiento(int idEstablecimiento) {
        this.idEstablecimiento = idEstablecimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(String dependencia) {
        this.dependencia = dependencia;
    }
    public String getTipologia() {
        return this.tipologia;
    }
    
    public void setTipologia(String tipologia) {
        this.tipologia = tipologia;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getOrigenDeFinanciamiento() {
        return this.origenDeFinanciamiento;
    }
    
    public void setOrigenDeFinanciamiento(String origenDeFinanciamiento) {
        this.origenDeFinanciamiento = origenDeFinanciamiento;
    }
    public Short getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Short nivel) {
        this.nivel = nivel;
    }
    public Set getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set cargos) {
        this.cargos = cargos;
    }
    public Set getTribunalJurados() {
        return this.tribunalJurados;
    }
    
    public void setTribunalJurados(Set tribunalJurados) {
        this.tribunalJurados = tribunalJurados;
    }




}


