package dominio;
// Generated 24/07/2015 09:37:24 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente  implements java.io.Serializable {


     private String numeroExpediente;
     private UnidadDeOrganizacion unidadDeOrganizacion;
     private Integer idExpediente;
     private Integer numero;
     private String situacion;
     private String regimen;
     private Integer anio;
     private Set resolucions = new HashSet(0);

    public Expediente() {
    }

	
    public Expediente(String numeroExpediente) {
        this.numeroExpediente = numeroExpediente;
    }
    public Expediente(String numeroExpediente, UnidadDeOrganizacion unidadDeOrganizacion, Integer idExpediente, Integer numero, String situacion, String regimen, Integer anio, Set resolucions) {
       this.numeroExpediente = numeroExpediente;
       this.unidadDeOrganizacion = unidadDeOrganizacion;
       this.idExpediente = idExpediente;
       this.numero = numero;
       this.situacion = situacion;
       this.regimen = regimen;
       this.anio = anio;
       this.resolucions = resolucions;
    }

    public Expediente(String numeroExpediente, UnidadDeOrganizacion unidadDeOrganizacion, Integer idExpediente, Integer numero, String situacion, String regimen, Integer anio) {
        this.numeroExpediente = numeroExpediente;
        this.unidadDeOrganizacion = unidadDeOrganizacion;
        this.idExpediente = idExpediente;
        this.numero = numero;
        this.situacion = situacion;
        this.regimen = regimen;
        this.anio = anio;
    }
   
    
    
    
    public String getNumeroExpediente() {
        return this.numeroExpediente;
    }
    
    public void setNumeroExpediente(String numeroExpediente) {
        this.numeroExpediente = numeroExpediente;
    }
    public UnidadDeOrganizacion getUnidadDeOrganizacion() {
        return this.unidadDeOrganizacion;
    }
    
    public void setUnidadDeOrganizacion(UnidadDeOrganizacion unidadDeOrganizacion) {
        this.unidadDeOrganizacion = unidadDeOrganizacion;
    }
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(String situacion) {
        this.situacion = situacion;
    }
    public String getRegimen() {
        return this.regimen;
    }
    
    public void setRegimen(String regimen) {
        this.regimen = regimen;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public Set getResolucions() {
        return this.resolucions;
    }
    
    public void setResolucions(Set resolucions) {
        this.resolucions = resolucions;
    }

    @Override
    public String toString() {
        return "Expediente{" + "numeroExpediente=" + numeroExpediente + ", unidadDeOrganizacion=(" + unidadDeOrganizacion.getCodigoUnidadDeOrganizacion() + ") " +  unidadDeOrganizacion.getNombreUnidad() + ", idExpediente=" + idExpediente + ", numero=" + numero + ", situacion=" + situacion + ", regimen=" + regimen + ", anio=" + anio + '}';
    }
    
    public boolean esValido(){
        boolean esValido = false;
        if(this.idExpediente != null && !this.numeroExpediente.equals("") && this.unidadDeOrganizacion != null && this.numero != null && !this.regimen.equals("") && !this.situacion.equals("")){
            esValido = true;
        }
        return esValido;
    }




}


