package dominio;
// Generated 24/08/2015 09:04:43 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente implements java.io.Serializable {

    private int idExpediente;
    private UnidadDeOrganizacion unidadDeOrganizacion;
    private Integer numero;
    private String situacion;
    private String regimen;
    private Integer anio;
    private String numeroExpediente;
    private Set resolucions = new HashSet(0);

    public Expediente() {
    }

    public Expediente(int idExpediente, String numeroExpediente) {
        this.idExpediente = idExpediente;
        this.numeroExpediente = numeroExpediente;
    }

    public Expediente(UnidadDeOrganizacion unidadDeOrganizacion, Integer numero, String situacion, String regimen, Integer anio, String numeroExpediente) {
        this.unidadDeOrganizacion = unidadDeOrganizacion;
        this.numero = numero;
        this.situacion = situacion;
        this.regimen = regimen;
        this.anio = anio;
        this.numeroExpediente = numeroExpediente;
    }

    public Expediente(int idExpediente, UnidadDeOrganizacion unidadDeOrganizacion, Integer numero, String situacion, String regimen, Integer anio, String numeroExpediente) {
        this.idExpediente = idExpediente;
        this.unidadDeOrganizacion = unidadDeOrganizacion;
        this.numero = numero;
        this.situacion = situacion;
        this.regimen = regimen;
        this.anio = anio;
        this.numeroExpediente = numeroExpediente;
    }

    public Expediente(int idExpediente, UnidadDeOrganizacion unidadDeOrganizacion, Integer numero, String situacion, String regimen, Integer anio, String numeroExpediente, Set resolucions) {
        this.idExpediente = idExpediente;
        this.unidadDeOrganizacion = unidadDeOrganizacion;
        this.numero = numero;
        this.situacion = situacion;
        this.regimen = regimen;
        this.anio = anio;
        this.numeroExpediente = numeroExpediente;
        this.resolucions = resolucions;
    }

    public int getIdExpediente() {
        return this.idExpediente;
    }

    public void setIdExpediente(int idExpediente) {
        this.idExpediente = idExpediente;
    }

    public UnidadDeOrganizacion getUnidadDeOrganizacion() {
        return this.unidadDeOrganizacion;
    }

    public void setUnidadDeOrganizacion(UnidadDeOrganizacion unidadDeOrganizacion) {
        this.unidadDeOrganizacion = unidadDeOrganizacion;
    }

    public Integer getNumero() {
        return this.numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    public String getSituacion() {
        return this.situacion;
    }

    public void setSituacion(String situacion) {
        this.situacion = situacion;
    }

    public String getRegimen() {
        return this.regimen;
    }

    public void setRegimen(String regimen) {
        this.regimen = regimen;
    }

    public Integer getAnio() {
        return this.anio;
    }

    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    public String getNumeroExpediente() {
        return this.numeroExpediente;
    }

    public void setNumeroExpediente(String numeroExpediente) {
        this.numeroExpediente = numeroExpediente;
    }

    public Set getResolucions() {
        return this.resolucions;
    }

    public void setResolucions(Set resolucions) {
        this.resolucions = resolucions;
    }

    public boolean esValido(){
        boolean resp = false;
        if(!numeroExpediente.equals("") && numero != 0 && !regimen.equalsIgnoreCase("") && !situacion.equalsIgnoreCase("") && anio != 0 && unidadDeOrganizacion != null){
            resp = true;
        }
        return resp;
    }  

    @Override
    public String toString() {
        return "Expediente{" + "unidadDeOrganizacion=" + unidadDeOrganizacion.getNombreUnidad() + ", numero=" + numero + ", situacion=" + situacion + ", regimen=" + regimen + ", anio=" + anio + ", numeroExpediente=" + numeroExpediente + '}';
    }
    
    
    
}
