package dominio;
// Generated 24/08/2015 09:04:43 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Institucion generated by hbm2java
 */
public class Institucion  implements java.io.Serializable {


     private int idInstitucion;
     private String nombreInstitucion;
     private String direccion;
     private String telefono;
     private Integer idLocalidad;
     private Set tribunalJurados = new HashSet(0);

    public Institucion() {
    }

	
    public Institucion(int idInstitucion) {
        this.idInstitucion = idInstitucion;
    }
    public Institucion(int idInstitucion, String nombreInstitucion, String direccion, String telefono, Integer idLocalidad, Set tribunalJurados) {
       this.idInstitucion = idInstitucion;
       this.nombreInstitucion = nombreInstitucion;
       this.direccion = direccion;
       this.telefono = telefono;
       this.idLocalidad = idLocalidad;
       this.tribunalJurados = tribunalJurados;
    }
   
    public int getIdInstitucion() {
        return this.idInstitucion;
    }
    
    public void setIdInstitucion(int idInstitucion) {
        this.idInstitucion = idInstitucion;
    }
    public String getNombreInstitucion() {
        return this.nombreInstitucion;
    }
    
    public void setNombreInstitucion(String nombreInstitucion) {
        this.nombreInstitucion = nombreInstitucion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
    public Set getTribunalJurados() {
        return this.tribunalJurados;
    }
    
    public void setTribunalJurados(Set tribunalJurados) {
        this.tribunalJurados = tribunalJurados;
    }




}


