package dominio;
// Generated 24/07/2015 09:37:24 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private long codigoLocalidad;
     private int idLocalidad;
     private String nombreDeLocalidad;
     private Short cp;
     private Boolean indec;
     private Integer idDepartamento;
     private Set personasForLocalidadNacimiento = new HashSet(0);
     private Set personasForIdLocalidadDireccion = new HashSet(0);

    public Localidad() {
    }

    public Localidad(long codigoLocalidad) {
        this.codigoLocalidad = codigoLocalidad;
    }


    
    
    
    public Localidad(long codigoLocalidad, int idLocalidad, String nombreDeLocalidad) {
        this.codigoLocalidad = codigoLocalidad;
        this.idLocalidad = idLocalidad;
        this.nombreDeLocalidad = nombreDeLocalidad;
    }
    public Localidad(long codigoLocalidad, int idLocalidad, String nombreDeLocalidad, Short cp, Boolean indec, Integer idDepartamento, Set personasForLocalidadNacimiento, Set personasForIdLocalidadDireccion) {
       this.codigoLocalidad = codigoLocalidad;
       this.idLocalidad = idLocalidad;
       this.nombreDeLocalidad = nombreDeLocalidad;
       this.cp = cp;
       this.indec = indec;
       this.idDepartamento = idDepartamento;
       this.personasForLocalidadNacimiento = personasForLocalidadNacimiento;
       this.personasForIdLocalidadDireccion = personasForIdLocalidadDireccion;
    }
   
    public long getCodigoLocalidad() {
        return this.codigoLocalidad;
    }
    
    public void setCodigoLocalidad(long codigoLocalidad) {
        this.codigoLocalidad = codigoLocalidad;
    }
    public int getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(int idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
    public String getNombreDeLocalidad() {
        return this.nombreDeLocalidad;
    }
    
    public void setNombreDeLocalidad(String nombreDeLocalidad) {
        this.nombreDeLocalidad = nombreDeLocalidad;
    }
    public Short getCp() {
        return this.cp;
    }
    
    public void setCp(Short cp) {
        this.cp = cp;
    }
    public Boolean getIndec() {
        return this.indec;
    }
    
    public void setIndec(Boolean indec) {
        this.indec = indec;
    }
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Set getPersonasForLocalidadNacimiento() {
        return this.personasForLocalidadNacimiento;
    }
    
    public void setPersonasForLocalidadNacimiento(Set personasForLocalidadNacimiento) {
        this.personasForLocalidadNacimiento = personasForLocalidadNacimiento;
    }
    public Set getPersonasForIdLocalidadDireccion() {
        return this.personasForIdLocalidadDireccion;
    }
    
    public void setPersonasForIdLocalidadDireccion(Set personasForIdLocalidadDireccion) {
        this.personasForIdLocalidadDireccion = personasForIdLocalidadDireccion;
    }




}


