package dominio;
// Generated 22/07/2015 11:18:12 by Hibernate Tools 3.6.0



/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private int idPersonal;
     private Integer dni;
     private String profesion;
     private String tipo;
     private String numeroMatricula;

    public Personal() {
    }

	
    public Personal(int idPersonal) {
        this.idPersonal = idPersonal;
    }
    public Personal(int idPersonal, Integer dni, String profesion, String tipo, String numeroMatricula) {
       this.idPersonal = idPersonal;
       this.dni = dni;
       this.profesion = profesion;
       this.tipo = tipo;
       this.numeroMatricula = numeroMatricula;
    }
   
    public int getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNumeroMatricula() {
        return this.numeroMatricula;
    }
    
    public void setNumeroMatricula(String numeroMatricula) {
        this.numeroMatricula = numeroMatricula;
    }




}


