package dominio;
// Generated 26/08/2015 11:54:39 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private Localidad localidadByLocalidadNacimiento;
     private Localidad localidadByIdLocalidadDireccion;
     private Integer dni;
     private String nombres;
     private String apellido;
     private String sexo;
     private String nacionalidad;
     private Date fechaDeNacimiento;
     private String direccion;
     private String telefono;
     private String email;
     private Long cuil;
     private Set personals = new HashSet(0);
     private Set tribunalJurados = new HashSet(0);
     private Set postulantes = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int idPersona) {
        this.idPersona = idPersona;
    }

    public Persona(String sexo) {
        this.sexo = sexo;
    }

    public Persona(int idPersona, String sexo) {
        this.idPersona = idPersona;
        this.sexo = sexo;
    }
    
    
    
    
    
    public Persona(int idPersona, Localidad localidadByLocalidadNacimiento, Localidad localidadByIdLocalidadDireccion, Integer dni, String nombres, String apellido, String sexo, String nacionalidad, Date fechaDeNacimiento, String direccion, String telefono, String email, Long cuil, Set personals, Set tribunalJurados, Set postulantes) {
       this.idPersona = idPersona;
       this.localidadByLocalidadNacimiento = localidadByLocalidadNacimiento;
       this.localidadByIdLocalidadDireccion = localidadByIdLocalidadDireccion;
       this.dni = dni;
       this.nombres = nombres;
       this.apellido = apellido;
       this.sexo = sexo;
       this.nacionalidad = nacionalidad;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.cuil = cuil;
       this.personals = personals;
       this.tribunalJurados = tribunalJurados;
       this.postulantes = postulantes;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Localidad getLocalidadByLocalidadNacimiento() {
        return this.localidadByLocalidadNacimiento;
    }
    
    public void setLocalidadByLocalidadNacimiento(Localidad localidadByLocalidadNacimiento) {
        this.localidadByLocalidadNacimiento = localidadByLocalidadNacimiento;
    }
    public Localidad getLocalidadByIdLocalidadDireccion() {
        return this.localidadByIdLocalidadDireccion;
    }
    
    public void setLocalidadByIdLocalidadDireccion(Localidad localidadByIdLocalidadDireccion) {
        this.localidadByIdLocalidadDireccion = localidadByIdLocalidadDireccion;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    
    public void setFechaDeNacimiento(Date fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Long getCuil() {
        return this.cuil;
    }
    
    public void setCuil(Long cuil) {
        this.cuil = cuil;
    }
    
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }
    public Set getTribunalJurados() {
        return this.tribunalJurados;
    }
    
    public void setTribunalJurados(Set tribunalJurados) {
        this.tribunalJurados = tribunalJurados;
    }
    public Set getPostulantes() {
        return this.postulantes;
    }
    
    public void setPostulantes(Set postulantes) {
        this.postulantes = postulantes;
    }

    public boolean datoVacio(String dato){
        boolean datoVacio = false;
        if(dato.isEmpty()){
            datoVacio = true;
        }
        return datoVacio;
    }

    @Override
    public String toString() {
        return "Persona " + idPersona + "{dni=" + dni + ", nombres=" + nombres + ", apellido=" + apellido + ", sexo=" + sexo + ", nacionalidad=" + nacionalidad + ", fechaDeNacimiento=" + fechaDeNacimiento + ", direccion=" + direccion + ", telefono=" + telefono + ", email=" + email + ", cuil=" + cuil + '}';
    }

    

    

}


