package dominio;
// Generated 24/08/2015 09:04:43 by Hibernate Tools 3.6.0

/**
 * Postulante generated by hbm2java
 */
public class Postulante implements java.io.Serializable {

    private int idPostulante;
    private Cargo cargo;
    private Persona persona;
    private Integer fojas;
    private Double antecedentes;
    private Double oposicion;
    private Double puntaje;

    public Postulante() {
    }

    public Postulante(Persona persona) {
        this.persona = persona;
    }

    public Postulante(int idPostulante, Cargo cargo, Persona persona) {
        this.idPostulante = idPostulante;
        this.cargo = cargo;
        this.persona = persona;
    }

    public Postulante(int idPostulante, Cargo cargo, Persona persona, Integer fojas, Double antecedentes, Double oposicion, Double puntaje) {
        this.idPostulante = idPostulante;
        this.cargo = cargo;
        this.persona = persona;
        this.fojas = fojas;
        this.antecedentes = antecedentes;
        this.oposicion = oposicion;
        this.puntaje = puntaje;
    }

    public int getIdPostulante() {
        return this.idPostulante;
    }

    public void setIdPostulante(int idPostulante) {
        this.idPostulante = idPostulante;
    }

    public Cargo getCargo() {
        return this.cargo;
    }

    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Integer getFojas() {
        return this.fojas;
    }

    public void setFojas(Integer fojas) {
        this.fojas = fojas;
    }

    public Double getAntecedentes() {
        return this.antecedentes;
    }

    public void setAntecedentes(Double antecedentes) {
        this.antecedentes = antecedentes;
    }

    public Double getOposicion() {
        return this.oposicion;
    }

    public void setOposicion(Double oposicion) {
        this.oposicion = oposicion;
    }

    public Double getPuntaje() {
        return this.puntaje;
    }

    public void setPuntaje(Double puntaje) {
        this.puntaje = puntaje;
    }

    @Override
    public String toString() {
        return "Postulante{" + "cargo=" + cargo.getFuncion() + ", persona=" + persona.getDni() + ", " + persona.getApellido()  + ", fojas=" + fojas + ", antecedentes=" + antecedentes + ", oposicion=" + oposicion + ", puntaje=" + puntaje + '}';
    }
    
    

}
