package dominio;
// Generated 22/07/2015 11:18:12 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Profesion generated by hbm2java
 */
public class Profesion  implements java.io.Serializable {


     private int idProfesion;
     private Integer codigoSiisa;
     private String nombreProfesion;
     private String profesionRefencia;
     private String formacion;
     private Boolean profesionColegiada;
     private Boolean profesionDeSalud;
     private String categoria;
     private Set cargos = new HashSet(0);

    public Profesion() {
    }

	
    public Profesion(int idProfesion) {
        this.idProfesion = idProfesion;
    }
    public Profesion(int idProfesion, Integer codigoSiisa, String nombreProfesion, String profesionRefencia, String formacion, Boolean profesionColegiada, Boolean profesionDeSalud, String categoria, Set cargos) {
       this.idProfesion = idProfesion;
       this.codigoSiisa = codigoSiisa;
       this.nombreProfesion = nombreProfesion;
       this.profesionRefencia = profesionRefencia;
       this.formacion = formacion;
       this.profesionColegiada = profesionColegiada;
       this.profesionDeSalud = profesionDeSalud;
       this.categoria = categoria;
       this.cargos = cargos;
    }
   
    public int getIdProfesion() {
        return this.idProfesion;
    }
    
    public void setIdProfesion(int idProfesion) {
        this.idProfesion = idProfesion;
    }
    public Integer getCodigoSiisa() {
        return this.codigoSiisa;
    }
    
    public void setCodigoSiisa(Integer codigoSiisa) {
        this.codigoSiisa = codigoSiisa;
    }
    public String getNombreProfesion() {
        return this.nombreProfesion;
    }
    
    public void setNombreProfesion(String nombreProfesion) {
        this.nombreProfesion = nombreProfesion;
    }
    public String getProfesionRefencia() {
        return this.profesionRefencia;
    }
    
    public void setProfesionRefencia(String profesionRefencia) {
        this.profesionRefencia = profesionRefencia;
    }
    public String getFormacion() {
        return this.formacion;
    }
    
    public void setFormacion(String formacion) {
        this.formacion = formacion;
    }
    public Boolean getProfesionColegiada() {
        return this.profesionColegiada;
    }
    
    public void setProfesionColegiada(Boolean profesionColegiada) {
        this.profesionColegiada = profesionColegiada;
    }
    public Boolean getProfesionDeSalud() {
        return this.profesionDeSalud;
    }
    
    public void setProfesionDeSalud(Boolean profesionDeSalud) {
        this.profesionDeSalud = profesionDeSalud;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set cargos) {
        this.cargos = cargos;
    }




}


