package dominio;
// Generated 24/07/2015 09:37:24 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tribunal generated by hbm2java
 */
public class Tribunal  implements java.io.Serializable {


     private int idTribunal;
     private Short cantidadMiembros;
     private Set tribunalJurados = new HashSet(0);
     private Set resolucions = new HashSet(0);

    public Tribunal() {
    }

	
    public Tribunal(int idTribunal) {
        this.idTribunal = idTribunal;
    }
    public Tribunal(int idTribunal, Short cantidadMiembros, Set tribunalJurados, Set resolucions) {
       this.idTribunal = idTribunal;
       this.cantidadMiembros = cantidadMiembros;
       this.tribunalJurados = tribunalJurados;
       this.resolucions = resolucions;
    }
   
    public int getIdTribunal() {
        return this.idTribunal;
    }
    
    public void setIdTribunal(int idTribunal) {
        this.idTribunal = idTribunal;
    }
    public Short getCantidadMiembros() {
        return this.cantidadMiembros;
    }
    
    public void setCantidadMiembros(Short cantidadMiembros) {
        this.cantidadMiembros = cantidadMiembros;
    }
    public Set getTribunalJurados() {
        return this.tribunalJurados;
    }
    
    public void setTribunalJurados(Set tribunalJurados) {
        this.tribunalJurados = tribunalJurados;
    }
    public Set getResolucions() {
        return this.resolucions;
    }
    
    public void setResolucions(Set resolucions) {
        this.resolucions = resolucions;
    }




}


