package dominio;
// Generated 26/08/2015 11:54:39 by Hibernate Tools 3.6.0



/**
 * TribunalJurado generated by hbm2java
 */
public class TribunalJurado  implements java.io.Serializable {


     private int idTribunalJurado;
     private Institucion institucion;
     private Persona persona;
     private Establecimiento establecimiento;
     private Tribunal tribunal;
     private String estado;
     private Boolean presencia;
     private String condicion;

    public TribunalJurado() {
    }

    public TribunalJurado(Institucion institucion, Persona persona, Establecimiento establecimiento, Tribunal tribunal, String estado, Boolean presencia, String condicion) {
        this.institucion = institucion;
        this.persona = persona;
        this.establecimiento = establecimiento;
        this.tribunal = tribunal;
        this.estado = estado;
        this.presencia = presencia;
        this.condicion = condicion;
    }

    
	
    public TribunalJurado(int idTribunalJurado) {
        this.idTribunalJurado = idTribunalJurado;
    }
    public TribunalJurado(int idTribunalJurado, Institucion institucion, Persona persona, Establecimiento establecimiento, Tribunal tribunal, String estado, Boolean presencia, String condicion) {
       this.idTribunalJurado = idTribunalJurado;
       this.institucion = institucion;
       this.persona = persona;
       this.establecimiento = establecimiento;
       this.tribunal = tribunal;
       this.estado = estado;
       this.presencia = presencia;
       this.condicion = condicion;
    }
   
    public int getIdTribunalJurado() {
        return this.idTribunalJurado;
    }
    
    public void setIdTribunalJurado(int idTribunalJurado) {
        this.idTribunalJurado = idTribunalJurado;
    }
    public Institucion getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(Institucion institucion) {
        this.institucion = institucion;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public Tribunal getTribunal() {
        return this.tribunal;
    }
    
    public void setTribunal(Tribunal tribunal) {
        this.tribunal = tribunal;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Boolean getPresencia() {
        return this.presencia;
    }
    
    public void setPresencia(Boolean presencia) {
        this.presencia = presencia;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    @Override
    public String toString() {
        return "TribunalJurado " + idTribunalJurado + "{institucion=(" + institucion.getIdInstitucion() + ") " + institucion.getNombreInstitucion() + ", persona=(" + persona.getIdPersona() + ") " + persona.getDni() + " - " + persona.getApellido() + ", establecimiento=(" + establecimiento.getCodigoSiisa() + ") " + establecimiento.getNombre() + ", tribunal=" + tribunal.getIdTribunal() + ", estado=" + estado + ", presencia=" + presencia + ", condicion=" + condicion + '}';
    }


}


