package dominio;
// Generated 26/08/2015 11:54:39 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * UnidadDeOrganizacion generated by hbm2java
 */
public class UnidadDeOrganizacion implements java.io.Serializable {

    private int idUnidadOrganizacion;
    private String nombreUnidad;
    private int codigoUnidadDeOrganizacion;
    private Set expedientes = new HashSet(0);

    public UnidadDeOrganizacion() {
    }

    public UnidadDeOrganizacion(int idUnidadOrganizacion) {
        this.idUnidadOrganizacion = idUnidadOrganizacion;
    }

    public UnidadDeOrganizacion(int idUnidadOrganizacion, String nombreUnidad, int codigoUnidadDeOrganizacion) {
        this.idUnidadOrganizacion = idUnidadOrganizacion;
        this.nombreUnidad = nombreUnidad;
        this.codigoUnidadDeOrganizacion = codigoUnidadDeOrganizacion;
    }

    public UnidadDeOrganizacion(int idUnidadOrganizacion, String nombreUnidad, int codigoUnidadDeOrganizacion, Set expedientes) {
        this.idUnidadOrganizacion = idUnidadOrganizacion;
        this.nombreUnidad = nombreUnidad;
        this.codigoUnidadDeOrganizacion = codigoUnidadDeOrganizacion;
        this.expedientes = expedientes;
    }

    public int getIdUnidadOrganizacion() {
        return this.idUnidadOrganizacion;
    }

    public void setIdUnidadOrganizacion(int idUnidadOrganizacion) {
        this.idUnidadOrganizacion = idUnidadOrganizacion;
    }

    public String getNombreUnidad() {
        return this.nombreUnidad;
    }

    public void setNombreUnidad(String nombreUnidad) {
        this.nombreUnidad = nombreUnidad;
    }

    public int getCodigoUnidadDeOrganizacion() {
        return this.codigoUnidadDeOrganizacion;
    }

    public void setCodigoUnidadDeOrganizacion(int codigoUnidadDeOrganizacion) {
        this.codigoUnidadDeOrganizacion = codigoUnidadDeOrganizacion;
    }

    public Set getExpedientes() {
        return this.expedientes;
    }

    public void setExpedientes(Set expedientes) {
        this.expedientes = expedientes;
    }

}
